### ISSUE TITLE
Update README.md with project description

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#10]

**Comment by miniatureseal** [comment]
Dependent on #6

**Comment by miniatureseal** [comment]
- the project title
- a short summary of the project (view from 10,000 feet) 
- how to run your data analysis 
- a list of the dependencies needed to run your analysis

=> this document should live in the root of your public GitHub.com repo.

**Comment by Rz02** [comment]
https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/27

**Comment by miniatureseal** [comment]
Added description how to run the analysis file: #39
With that this issue is done!
