### ISSUE TITLE
Add an exiting data analysis in a single juypter notebook

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#12]
For this milestone, the analysis code and narration should be contained within a single literate code document (i.e., Jupyter notebook). This document should not actually be named analysis.ipynb, but have a more descriptive title, related to the project title.

Requirements:
For this milestone, the analysis code and narration should be contained within a single literate code document (i.e., Jupyter notebook). The following sections should be included:

# Title
## Introduction:
- provide some relevant background information on the topic so that someone unfamiliar with it will be prepared to - understand the rest of your report
- clearly state the question you tried to answer with your project
- identify and describe the dataset that was used to answer the question
## Methods & Results:
- describe in written english the methods you used to perform your analysis from beginning to end that narrates the code the does the analysis.
- your report should include code which:
- loads data from the original source on the web
- wrangles and cleans the data from it’s original (downloaded) format to the format necessary for the planned classification or clustering analysis
- performs a summary of the data set that is relevant for exploratory data analysis related to the planned classification analysis
- creates a visualization of the dataset that is relevant for exploratory data analysis related to the planned classification analysis
- performs classification or regression analysis
- creates a visualization of the result of the analysis
- note: all tables and figure should have a figure/table number and a legend
## Discussion:
- summarize what you found
- discuss whether this is what you expected to find?
- discuss what impact could such findings have?
- discuss what future questions could this lead to?
## References:
- at least 4 citations relevant to the project (format is your choose, just be consistent across the references).

**Comment by miniatureseal** [comment]
Dependent on #6

**Comment by miniatureseal** [comment]
This task can also be used to split the analysis up into separate chunks which can then be worked on by other team members

**Comment by miniatureseal** [comment]
Added the dsci100 project which @Rz02 worked on

**Comment by miniatureseal** [comment]
Reopened issue because some milestone goals were missing

**Comment by Rz02** [comment]
https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/24
