### ISSUE TITLE
Implement auto publishing of docker file

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#14]
In this milestone, we expect you to add a GitHub Actions workflow to automatically build the image, push it to DockerHub, and version the image and GitHub repo when changes are pushed to the Dockerfile ([link to a GitHub Actions Workflow you should use for this](https://github.com/ttimbers/dockerfile-practice/blob/main/.github/workflows/publish_docker_image.yml)). When setting up the workflow on GitHub Actions, be sure to click “Skip this and setup a workflow yourself”. You will need to add your DockerHub username and password (naming them DOCKER_USERNAME and DOCKER_PASSWORD, respectively) as GitHub secrets to this repository for this to work.

For this project, we will be making the computation environment reproducible through containerization with Docker. We will use Docker containers for collaborative project development, as well as for sharing a reproducible analysis at the end of the project. It is expected that: - the Docker image, from which containers are generated, will be specified by a Dockerfile that lives in the root of the project’s GitHub repository - the building of the Docker image and distribution of it via DockerHub will be automated via GitHub Actions - an explanation of how to run and use Docker to develop and execute the analysis will be documented in the README.md file.

**Comment by jh22d** [comment]
update the readme file. https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/39
