### ISSUE TITLE
Milestone 1 end: Add a new release

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#15]
Just before you submit the milestone 1, create a release on your project repository on GitHub and name it 0.0.1 ([how to create a release](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release)). This release allows us and you to easily jump to the state of your repository at the time of submission for grading puroposes, while you continue to work on your project for the next milestone.

**Comment by Rz02** [comment]
Release has been done.
