### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by chris-ckh** [miniatureseal/dsci-310-group-10-GCC#152]
### Conflict of interest
 
- [✓] As the reviewer I confirm that I have no conflicts of interest for me to review this work.
 
### Code of Conduct
 
- [✓] I confirm that I read and will adhere to the [MDS code of conduct](https://ubc-mds.github.io/resources_pages/code_of_conduct/).
 
### General checks
 
- [✓] **Repository:** Is the source code for this data analysis available? Is the repository well organized and easy to navigate?
- [✓] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?
 
### Documentation
 
- [✓] **Installation instructions:** Is there a clearly stated list of dependencies?
There is a list of dependencies, but under a section called “Running the project locally
” instead of an individual section named “Dependencies”
- [✓] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [✓] **Functionality documentation:** Is the core functionality of the data analysis software documented to a satisfactory level?
- [✓] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
 
### Code quality
- [✓] **Readability:** Are scripts, functions, objects, etc., well named? Is it relatively easy to understand the code?
- [✓] **Style guidelines:** Does the code adhere to well known language style guides?
- [✓] **Modularity:** Is the code suitably abstracted into scripts and functions?
- [✓] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robustness?
 
### Reproducibility
 
- [✓] **Data:** Is the raw data archived somewhere? Is it accessible?
- [✓] **Computational methods:** Is all the source code required for the data analysis available?
- [✓] **Conditions:** Is there a record of the necessary conditions (software dependencies) needed to reproduce the analysis? Does there exist an easy way to obtain the computational environment needed to reproduce the analysis?
- [✓] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?
 
### Analysis report
 
- [✓] **Authors:** Does the report include a list of authors with their affiliations?
- [✓] **What is the question:** Do the authors clearly state the research question being asked?
- [✓] **Importance:** Do the authors clearly state the importance for this research question?
- [✓] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [✘] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [✓] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [✓] **Conclusions:** Are the conclusions presented by the authors correct?
- [✓] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [✓] **Writing quality:** Is the writing of good quality, concise, engaging?
 
### Review Comments:
 
Please provide more detailed feedback here on what was done particularly well, and what could be improved. It is especially important to elaborate on items that you were not able to check off in the list above.

- The report can be run reproducibly with commands provided in README. 

- The confusion matrix does not match with the text below. For example, the matrix only seems to provide the results predicted by the model as FP and FN are all 0 which is almost impossible while in the text below, it is said that “[the model] predicted not fire correctly in 25 cases, predicted fire correctly in 32 cases and predicted incorrectly in only 3 cases. ”. Therefore, I would doubt that something went wrong with the code which creates the confusion matrix (which does not have a chunk name). 

- The r chunk “entries-by-class” and the confusion matrix is not saved out by previous steps so it is still produced by code. Therefore, save out these tables or png files instead of still producing by code. This will likely reduce some of the time for “make all” to run.

- Maybe using “COPY” in dockerfile to put files that are required for the report instead of using volumes because it looks a little messy for the Rstudio container which also contains Dockerfile, Contributing, etc. These files are not required for producing the report in the container. 
- The limitations seem not to be included in the conclusion or in the report after discussing the results. 

 
#### Attribution
 
This was derived from the [JOSE review checklist](https://openjournals.readthedocs.io/en/jose/review_checklist.html) and the ROpenSci review checklist.
 

#### 
if the text above does not render correctly, please view this on:
https://docs.google.com/document/d/1VHSGKmrRRjxKUHFsHU71t34IBLMV98AaVtokeCh-iWY/edit?usp=sharing

**Comment by miniatureseal** [comment]
Concerning the following bullet point:

- Maybe using “COPY” in dockerfile to put files that are required for the report instead of using volumes because it looks a little messy for the Rstudio container which also contains Dockerfile, Contributing, etc. These files are not required for producing the report in the container.

I think that it is better to mount the whole volume, because if changes are made to the project inside of the container, they are also persisted on the local machine this way. If we would just COPY them, then the changes would be gone after closing the container if we didn't push them to a remote repository.

**Comment by miniatureseal** [comment]
We create the issues #171 #172 and #173 out of this peer review. These will be adressed accordingly. As we now have separate issues we will close this issue now. Thank you for your peer review 👍
