### ISSUE TITLE
Peer Review - mjbrodie

### ISSUE THREAD

**Issue by mjbrodie** [miniatureseal/dsci-310-group-10-GCC#156]
### Conflict of interest

- [✓] As the reviewer I confirm that I have no conflicts of interest for me to review this work.

### Code of Conduct

- [✓] I confirm that I read and will adhere to the [MDS code of conduct](https://ubc-mds.github.io/resources_pages/code_of_conduct/).

### General checks

- [✓] **Repository:** Is the source code for this data analysis available? Is the repository well organized and easy to navigate?
- [✓] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

### Documentation

- [✓] **Installation instructions:** Is there a clearly stated list of dependencies? 
- [✓] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [✓] **Functionality documentation:** Is the core functionality of the data analysis software documented to a satisfactory level?
- [✓] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Code quality
- [✓] **Readability:** Are scripts, functions, objects, etc., well named? Is it relatively easy to understand the code?
- [✓] **Style guidelides:** Does the code adhere to well known language style guides?
- [✓] **Modularity:** Is the code suitably abstracted into scripts and functions?
- [✓] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robsutness?

### Reproducibility
 
- [✓] **Data:** Is the raw data archived somewhere? Is it accessible?
- [✓] **Computational methods:** Is all the source code required for the data analysis available?
- [✓] **Conditions:** Is there a record of the necessary conditions (software dependencies) needed to reproduce the analysis? Does there exist an easy way to obtain the computational environment needed to reproduce the analysis?
- [✓] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?

### Analysis report

- [✓] **Authors:** Does the report include a list of authors with their affiliations?
- [✓] **What is the question:** Do the authors clearly state the research question being asked?
- [✓] **Importance:** Do the authors clearly state the importance for this research question?
- [✓] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [ X ] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [✓] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [✓] **Conclusions:** Are the conclusions presented by the authors correct? 
- [✓] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [✓] **Writing quality:** Is the writing of good quality, concise, engaging? 

### Review Comments: 

Please provide more detailed feedback here on what was done particularly well, and what could be improved. It is especially important to elaborate on items that you were not able to check off in the list above.

- The instructions on how to re-create the project locally were clearly detailed and thought-out. I did try to run the project via the URL method but ran into an error. I suspect this is more user-error than error from the instructions.

- Looking through the different R scripts I was pleased to see the extent of the comments in scripts 01, 02, & 03. 

- In the actual report I noticed that there was a reference to the Ws variable in Table 2.2.1 & 2.2.2. However, I only saw Table 2.2 and only saw the range of values referenced for when the Ws variable was between 8-21, but not when the Ws values were between 10-22. Is the first range of Ws values supposed to be for the class 'fire' and the second range supposed to be for the class 'not fire'? The 'not fire' class has values displayed in Table 2.3, but the Ws range of values is different than 10-22. Im not sure where the second range of values for Ws is coming from.

- All in all, this group did a great job with implementing a reproducible project and even though the actual content of the project isnt what is being graded I still enjoyed reading through the data and seeing the accuracy of being able to predict forest fires. 

#### Attribution

This was derived from the [JOSE review checklist](https://openjournals.readthedocs.io/en/jose/review_checklist.html) and the ROpenSci review checklist.

**Comment by miniatureseal** [comment]
Hi @mjbrodie can you please include the error mentioned in the first bullet point? Maybe we can help!

**Comment by miniatureseal** [comment]
The other issue mentioned will be adressed with #174

**Comment by miniatureseal** [comment]
As we address the problems mentioned in the linked issues we will close this issue.

**Comment by mjbrodie** [comment]
Hi @miniatureseal  -- I got this resolved. As I suspected, it was user error. Thank you for following up
