### ISSUE TITLE
Peer Review by Ng Ser Jie

### ISSUE THREAD

**Issue by ngserjie** [miniatureseal/dsci-310-group-10-GCC#157]
### Conflict of interest

- [✓ ] As the reviewer I confirm that I have no conflicts of interest for me to review this work.

### Code of Conduct

- [✓ ] I confirm that I read and will adhere to the [MDS code of conduct](https://ubc-mds.github.io/resources_pages/code_of_conduct/).

### General checks

- [✓ ] **Repository:** Is the source code for this data analysis available? Is the repository well organized and easy to navigate?
- [✓ ] **License:** Does the repository contain a plain-text LICENSE file with the contents of an [OSI approved](https://opensource.org/licenses/alphabetical) software license?

### Documentation

- [✓ ] **Installation instructions:** Is there a clearly stated list of dependencies? 
- [✓ ] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [✓ ] **Functionality documentation:** Is the core functionality of the data analysis software documented to a satisfactory level?
- [✓ ] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

### Code quality
- [✓ ] **Readability:** Are scripts, functions, objects, etc., well named? Is it relatively easy to understand the code?
- [✓ ] **Style guidelides:** Does the code adhere to well known language style guides?
- [✓ ] **Modularity:** Is the code suitably abstracted into scripts and functions?
- [✓ ] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robsutness?

### Reproducibility
 
- [✓ ] **Data:** Is the raw data archived somewhere? Is it accessible?
- [✓ ] **Computational methods:** Is all the source code required for the data analysis available?
- [✓ ] **Conditions:** Is there a record of the necessary conditions (software dependencies) needed to reproduce the analysis? Does there exist an easy way to obtain the computational environment needed to reproduce the analysis?
- [✓ ] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?

### Analysis report

- [✓ ] **Authors:** Does the report include a list of authors with their affiliations?
- [✓ ] **What is the question:** Do the authors clearly state the research question being asked?
- [✓ ] **Importance:** Do the authors clearly state the importance for this research question?
- [✓ ] **Background**: Do the authors provide sufficient background information so that readers can understand the report?
- [✘ ] **Methods:** Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?
- [✓ ] **Results:** Do the authors clearly communicate their findings through writing, tables and figures?
- [✓ ] **Conclusions:** Are the conclusions presented by the authors correct? 
- [✓ ] **References:** Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?
- [✓ ] **Writing quality:** Is the writing of good quality, concise, engaging? 

### Review Comments: 

Please provide more detailed feedback here on what was done particularly well, and what could be improved. It is especially important to elaborate on items that you were not able to check off in the list above.

- From the fifth paragraph of section 2 - Exploring the dataset, the table 2.2.1 and 2.2.2 are not shown in the report. The average values of 15.42 and 15.725 are not found in any tables below too and the way to calculate them or where to obtain these values are not stated in the report. Some sentences are cut-off by the tables in between. There is some plot(s) not generated after Table 5 as the paragraph below it mentions to see from a plot but there is no any plot provided in this part. 

- From the paragraph below Figure 3, it is confusing to see different variable “k”, lowercase k with italic and non-italic, uppercase K etc. Not sure if they are same variable or different variable. For the title of legend of Figure 4, does the “IS” means Initial Spread from ISI or an English verb “is”. The typo makes the report hard to read and confusing.

- The values provided in Table 7 does not match the values provided in the confusion matrix explanation in paragraph. The Table 6 is not explained and why is it needed. All of the table and graph explanations are not labelled with their numbers which make the reader confused on which one the explanation is referring to. It should mentions Table 7 as the confusion matrix etc. 

- Overall, good explanation in the report however there are some missing plots and mistakes in result values. Improvement can be done by double checking the explanation part and ensure the report generates all required tables and plots in the correct arrangements. The R script files have clear and descriptive comments which are easy to understand. The instructions given in readme are comprehensive to follow and run the report.

#### Attribution

This was derived from the [JOSE review checklist](https://openjournals.readthedocs.io/en/jose/review_checklist.html) and the ROpenSci review checklist.

**Comment by miniatureseal** [comment]
Issues will be adressed with #175 #177 #176 #174. This issue can thus be closed. Thank you for your review :)
