### ISSUE TITLE
0.1 fix the confusion matrix issue

### ISSUE THREAD

**Issue by jh22d** [miniatureseal/dsci-310-group-10-GCC#171]
The confusion matrix does not match with the text below. For example, the matrix only seems to provide the results predicted by the model as FP and FN are all 0 which is almost impossible while in the text below, it is said that “[the model] predicted not fire correctly in 25 cases, predicted fire correctly in 32 cases and predicted incorrectly in only 3 cases. ”. Therefore, I would doubt that something went wrong with the code which creates the confusion matrix (which does not have a chunk name).

The r chunk “entries-by-class” and the confusion matrix is not saved out by previous steps so it is still produced by code. Therefore, save out these tables or png files instead of still producing by code. This will likely reduce some of the time for “make all” to run.

**Comment by Rz02** [comment]
DONE
