### ISSUE TITLE
0.2 Add methodology discussion

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#172]
Answer the following questions in the report:
Do the authors clearly describe and justify the methodology used in the data analysis? Do the authors communicate any assumptions or limitations of their methodologies?

**Comment by jh22d** [comment]
https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/187

**Comment by miniatureseal** [comment]
Done with https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/187
