### ISSUE TITLE
0.5 fix the mis-match of values in the tables and in the context under '2 Exploring the dataset' and the typo

### ISSUE THREAD

**Issue by jh22d** [miniatureseal/dsci-310-group-10-GCC#175]
We can see from Table 2.2.1 and 2.2.2 that the range of values for Ws is really similar, which is 8-21 and `!10-22`. Their averages are also really similar, which are`!15.42` and `!15.725`. 

The same can be seen for the confusion matrix further down in the report.

**Comment by Rz02** [comment]
https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/186
