### ISSUE TITLE
1.1 Adapt the original repo to use the new repo as a package

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#188]
Also adapt the docker image so that it loads in repository from github as a package!

If everything works, including
- make all => documents generated
then we can start deleting the tests and functions from the old repository

**Comment by jh22d** [comment]
https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/191

**Comment by jh22d** [comment]
remember to modify docker container
