### ISSUE TITLE
Refit all file names to have a uniform naming scema and rename analysis file

### ISSUE THREAD

**Issue by Rz02** [miniatureseal/dsci-310-group-10-GCC#26]
Rename files like analysis.ipynb to forest_fire_prediction.ipynb, Written Permission.pdf to written_permission.pdf.

**Comment by miniatureseal** [comment]
PR open: https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/28

**Comment by miniatureseal** [comment]
PR closed, thus closing this ticket
