### ISSUE TITLE
Draft team work contract

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#4]
See for reference: https://ubc-dsci.github.io/dsci-310-student/sample-team-work-contract.html

We will write the team contract into this document: https://docs.google.com/document/d/1mg8IGLf3wtWFVM-_ZApg03Z35te-7wXVeA3zK4PfNCk/edit?usp=sharing

**Comment by Rz02** [comment]
The general structure has been built up in the google doc linked above. More content is expected to be filled in.

**Comment by jh22d** [comment]
it can be found in README.MD
