### ISSUE TITLE
Add a file CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by miniatureseal** [miniatureseal/dsci-310-group-10-GCC#7]
In an attempt to create a safe, positive, productive, and happy community, many organizations and developers create a code of conduct for their projects. A code of conduct in a Data Science project informs others of social norms, acceptable behaviour and general etiquette. It is more outward facing than the team work contract discussed above. We recommend [Project Include](https://projectinclude.org/writing_cocs) for a comprehensive guide to writing an effective Code of Conduct.

At minimum, we believe that a good/effective code of conduct should include:

A Statement on diversity and inclusivity
Details on expected, and unacceptable behaviour
A list of consequences for unacceptable behaviour
A procedure for reporting and dealing with unacceptable behaviour

Examples:
[UBC Data Science 100 CoC](https://github.com/UBC-DSCI/dsci-100/blob/master/CODE_OF_CONDUCT.md)
[idocde Coc](http://www.idocde.net/pages/35)
[Python Community CoC](https://www.python.org/psf/conduct/)
[Tidyverse CoC](https://github.com/tidyverse/tidyverse.org/blob/master/CODE_OF_CONDUCT.md)
[Pandas CoC](https://github.com/pandas-dev/pandas-governance/blob/master/code-of-conduct.md)
[Vox Media CoC](http://code-of-conduct.voxmedia.com/?_ga=1.62865454.308680892.1455143920)

The document should be situated in the ROOT directory

**Comment by jh22d** [comment]
https://github.com/miniatureseal/dsci-310-group-10-GCC/pull/23
